/* NBRC Respiratory Pharmacology Chart — medication data
   Edit this file to add or change drugs. Each entry:
   c = class key (see CATS), g = generic, b = brand(s), t = category label,
   opd = {on: onset, pk: peak, du: duration},
   str/dose/eff/adv/haz/dev/note = arrays of bullet points.
   W("Label") adds a red warning flag in front of a bullet. */
const CATS = {
  beta:  {n:"Sympathomimetic (Adrenergic / Beta Agonist)", s:"Stimulate β2 receptors → ↑ cAMP → smooth muscle relaxation"},
  anti:  {n:"Parasympatholytic (Anticholinergic)", s:"Block muscarinic receptors → ↓ cGMP → bronchodilation"},
  combo: {n:"Combinations", s:"Two agents in one device for adherence and additive effect"},
  xan:   {n:"Phosphodiesterase Inhibitors (Xanthines)", s:"Methylxanthines: bronchodilation + respiratory stimulation"},
  bio:   {n:"Biologics", s:"Monoclonal antibodies for severe, uncontrolled asthma"},
  masto: {n:"Anti-asthmatic (Mast Cell Stabilizer)", s:"Prevents mast cell degranulation; prophylactic only"},
  ltm:   {n:"Leukotriene Modifiers", s:"Oral anti-inflammatory controllers"},
  abx:   {n:"Anti-infectives", s:"Inhaled and systemic agents seen on the boards"},
  muco:  {n:"Mucolytics", s:"Thin secretions to aid clearance"},
  ster:  {n:"Corticosteroids", s:"Anti-inflammatory; inhaled (ICS) and systemic"},
  dil:   {n:"Diluents / Bland Aerosol", s:"Humidification, dilution, sputum induction"}
};
const K = c => `var(--c-${c})`;
const W = t => `<span class="flag">${t}</span>`;

const D = [
/* ---------- BETA AGONISTS ---------- */
{c:"beta",g:"Albuterol",opd:{on:"5–15 min",pk:"30–60 min",du:"4–6 hr"},b:"Proventil HFA, Ventolin HFA, ProAir HFA / RespiClick, AccuNeb",t:"SABA (short-acting β2 agonist)",
 str:["0.5% (5 mg/mL) concentrate","0.083% unit dose (2.5 mg/3 mL)","AccuNeb 0.021% & 0.042% (peds)","pMDI 90 mcg/puff","DPI 90 mcg/inh"],
 dose:["SVN: 2.5 mg (0.5 mL of 0.5% in 2.5–3 mL NS) TID–QID or q4–6h","pMDI/DPI: 2 puffs q4–6h PRN","Continuous neb: 10–15 mg/hr (acute severe asthma)"],
 eff:["Rapid, short-acting bronchodilation","Rescue for acute bronchospasm: asthma, COPD, EIB (2 puffs 15–30 min before exercise)","Also shifts K⁺ into cells (used for hyperkalemia)"],
 adv:["Tachycardia, palpitations","Tremor, nervousness, headache","Hypokalemia, hyperglycemia","Transient ↓ PaO₂ (V/Q mismatch)","Paradoxical bronchospasm"],
 haz:["Caution with cardiac disease, arrhythmias, HTN, hyperthyroid, diabetes","Stop treatment and notify physician if HR ↑ >20 beats/min or arrhythmia develops"],
 dev:["Nebulizer","pMDI","DPI"],
 note:["The go-to rescue inhaler and the most tested drug on the TMC","Assess breath sounds, HR, and peak flow before and after","Racemic mixture: R-isomer is active, S-isomer is not"]},
{c:"beta",g:"Levalbuterol",opd:{on:"10–15 min",pk:"30–90 min",du:"5–8 hr"},b:"Xopenex, Xopenex HFA",t:"SABA (R-isomer of albuterol)",
 str:["0.31 mg/3 mL, 0.63 mg/3 mL, 1.25 mg/3 mL unit dose","1.25 mg/0.5 mL concentrate","pMDI 45 mcg/puff"],
 dose:["SVN: 0.63 mg TID (q6–8h); up to 1.25 mg TID","Peds 6–11 yrs: 0.31 mg TID","pMDI: 2 puffs q4–6h PRN"],
 eff:["Same as albuterol: rapid, short-acting bronchodilation","Rescue for asthma / COPD bronchospasm"],
 adv:["Same class effects as albuterol, possibly less tachycardia and tremor"],
 haz:["Same cardiac precautions as albuterol","Store unit doses in foil pouch, protected from light"],
 dev:["Nebulizer","pMDI"],
 note:["Exam pick when a patient has tachycardia or palpitations on albuterol","Only the active (R) isomer, so a lower dose gives similar effect"]},
{c:"beta",g:"Racemic Epinephrine",opd:{on:"3–5 min",pk:"5–20 min",du:"0.5–2 hr"},b:"S2, AsthmaNefrin (racepinephrine)",t:"Adrenergic (α + β agonist)",
 str:["2.25% solution"],
 dose:["SVN: 0.25–0.5 mL of 2.25% in 3 mL NS, q3–4h PRN (up to QID)"],
 eff:["α1 vasoconstriction → shrinks airway mucosal edema (decongestion)","Some β bronchodilation","Post-extubation stridor, croup (laryngotracheobronchitis), upper airway edema"],
 adv:["Tachycardia, HTN, arrhythmias","Tremor, anxiety, headache","Rebound mucosal edema"],
 haz:["Observe for rebound stridor for 2–4 hr after treatment (croup patients should stay under observation)","Monitor HR and BP"],
 dev:["Nebulizer"],
 note:["Know the reason: the α effect decongests the upper airway","Board answer for post-extubation stridor alongside cool mist and possibly steroids"]},
{c:"beta",g:"Salmeterol",opd:{on:"~20 min",pk:"3–5 hr",du:"12 hr"},b:"Serevent Diskus",t:"LABA (long-acting β2 agonist)",
 str:["50 mcg/inhalation"],
 dose:["1 inhalation (50 mcg) BID, about 12 hr apart","EIB: 1 inh at least 30 min before exercise"],
 eff:["Maintenance bronchodilation (12 hr)","Asthma maintenance (with ICS) and COPD maintenance","Prevention of EIB"],
 adv:["Headache, tremor, tachycardia, palpitations","Throat irritation, cough"],
 haz:[W("Boxed warning")+"Never use as monotherapy in asthma; must be paired with an ICS (↑ asthma-related death risk alone)","Not for rescue (slow onset)","Do not exceed BID dosing"],
 dev:["DPI"],
 note:["Slow onset is why it is never a rescue drug","Diskus: do not exhale into device; keep level and dry"]},
{c:"beta",g:"Formoterol fumarate",opd:{on:"1–3 min",pk:"1–3 hr",du:"12 hr"},b:"Perforomist (neb); Foradil Aerolizer (discontinued)",t:"LABA",
 str:["Perforomist 20 mcg/2 mL","Foradil 12 mcg capsule"],
 dose:["SVN: 20 mcg BID (max 40 mcg/day)","DPI (Foradil): 12 mcg capsule BID"],
 eff:["Fast-onset, long-acting bronchodilation","COPD maintenance (Perforomist)"],
 adv:["Tremor, tachycardia, headache, nausea","Hypokalemia, hyperglycemia"],
 haz:[W("Boxed warning")+"LABA monotherapy in asthma is contraindicated","Not labeled for rescue in the US despite fast onset","Refrigerate Perforomist until dispensed"],
 dev:["Nebulizer","DPI"],
 note:["Fast onset LABA: key difference from salmeterol","Foradil capsules are punctured in the device, never swallowed"]},
{c:"beta",g:"Arformoterol",opd:{on:"7–20 min",pk:"1–3 hr",du:"12 hr"},b:"Brovana",t:"LABA (R,R-isomer of formoterol)",
 str:["15 mcg/2 mL unit dose"],
 dose:["SVN: 15 mcg BID (max 30 mcg/day)"],
 eff:["Long-acting bronchodilation, 12 hr","COPD maintenance (chronic bronchitis, emphysema)"],
 adv:["Pain, chest pain, back pain, diarrhea, leg cramps","Tachycardia, tremor, nervousness"],
 haz:["Not for acute bronchospasm","Not approved for asthma","Refrigerate; protect from light"],
 dev:["Nebulizer"],
 note:["Single-isomer version of formoterol, similar to levalbuterol vs albuterol","A nebulized LABA option for COPD patients who can't use a DPI"]},
{c:"beta",g:"Indacaterol",opd:{on:"~5 min",pk:"1–4 hr",du:"24 hr"},b:"Arcapta Neohaler",t:"Ultra-LABA (24-hr β2 agonist)",
 str:["75 mcg capsule for inhalation"],
 dose:["DPI: 75 mcg once daily"],
 eff:["Once-daily bronchodilation","COPD maintenance"],
 adv:["Cough right after inhalation (common)","Nasopharyngitis, headache, nausea","Tachycardia, tremor"],
 haz:["Not for asthma or acute symptoms","Capsule is punctured in the Neohaler, never swallowed"],
 dev:["DPI"],
 note:["Know it as the once-daily ultra-LABA","US brand has been discontinued but it still appears in texts and exam prep"]},
{c:"beta",g:"Olodaterol",opd:{on:"~5 min",pk:"1–3 hr",du:"24 hr"},b:"Striverdi Respimat",t:"Ultra-LABA (24-hr)",
 str:["2.5 mcg/actuation"],
 dose:["2 inhalations (5 mcg) once daily"],
 eff:["24-hr bronchodilation","COPD maintenance"],
 adv:["Nasopharyngitis, URI, cough","Back pain, dizziness","Tachycardia, tremor"],
 haz:["Not for asthma or rescue","Cartridge must be inserted and device primed before first use"],
 dev:["SMI (Respimat)"],
 note:["Respimat is a soft mist inhaler: slow, long-lasting mist, no propellant","Pairs with tiotropium in Stiolto Respimat"]},

/* ---------- ANTICHOLINERGICS ---------- */
{c:"anti",g:"Ipratropium bromide",opd:{on:"~15 min",pk:"1–2 hr",du:"4–6 hr"},b:"Atrovent HFA",t:"SAMA (short-acting muscarinic antagonist)",
 str:["0.02% solution (500 mcg/2.5 mL)","pMDI 17 mcg/puff"],
 dose:["SVN: 500 mcg TID–QID (q6–8h)","pMDI: 2 puffs QID (max 12 puffs/day)"],
 eff:["Short-acting bronchodilation","COPD maintenance","Added to SABA in acute asthma in the ED","Can ↓ secretions; nasal form for rhinorrhea"],
 adv:["Dry mouth, cough, headache","Blurred vision / pupil dilation if mist reaches eyes","Urinary retention, constipation"],
 haz:["Caution with narrow-angle glaucoma, BPH / bladder neck obstruction","Use a mouthpiece rather than mask, or shield the eyes"],
 dev:["Nebulizer","pMDI"],
 note:["Quaternary ammonium compound: poorly absorbed, so fewer systemic effects than atropine","Slower onset than albuterol: not first-line rescue alone"]},
{c:"anti",g:"Tiotropium bromide",opd:{on:"~30 min",pk:"~3 hr",du:"24 hr"},b:"Spiriva HandiHaler, Spiriva Respimat",t:"LAMA (long-acting muscarinic antagonist)",
 str:["HandiHaler 18 mcg capsule","Respimat 2.5 mcg/puff (COPD), 1.25 mcg/puff (asthma)"],
 dose:["HandiHaler: 18 mcg (1 capsule, 2 inhalations) once daily","Respimat: 2 puffs once daily (5 mcg COPD; 2.5 mcg asthma)"],
 eff:["24-hr bronchodilation","COPD maintenance; ↓ exacerbations","Respimat 1.25 mcg: add-on maintenance for asthma (≥6 yrs)"],
 adv:["Dry mouth (most common), constipation","URI, sinusitis, pharyngitis","Urinary retention, tachycardia, blurred vision"],
 haz:["Not for rescue","Narrow-angle glaucoma, BPH, urinary retention","Never swallow capsules; keep powder out of eyes"],
 dev:["DPI","SMI (Respimat)"],
 note:["The classic once-daily COPD maintenance drug","HandiHaler: inhale twice from each capsule to empty it"]},
{c:"anti",g:"Glycopyrrolate",opd:{on:"Inhaled: 5–15 min · IV: ~1 min",pk:"Inhaled: 1–2 hr",du:"Inhaled: 12 hr · IV: 2–7 hr"},b:"Lonhala Magnair (neb), Seebri Neohaler (DPI), Robinul (IV)",t:"LAMA",
 str:["Lonhala 25 mcg/1 mL vial","Seebri 15.6 mcg capsule","IV 0.2 mg/mL"],
 dose:["Neb: 25 mcg BID (Magnair only)","DPI: 15.6 mcg BID","IV: 0.1–0.2 mg for secretion reduction"],
 eff:["Maintenance bronchodilation in COPD","IV/IM: dries oral and airway secretions (pre-op, end of life, drooling)"],
 adv:["Dry mouth, UTI, cough, sinusitis","Urinary retention, blurred vision, tachycardia"],
 haz:["Not for rescue","Narrow-angle glaucoma, BPH","Lonhala is used only with the Magnair vibrating-mesh nebulizer"],
 dev:["Nebulizer","DPI","Injection"],
 note:["Quaternary amine: doesn't cross the blood-brain barrier","Appears in Bevespi and Breztri combos"]},
{c:"anti",g:"Umeclidinium bromide",opd:{on:"~15 min",pk:"~3 hr",du:"24 hr"},b:"Incruse Ellipta",t:"LAMA",
 str:["62.5 mcg/inhalation"],
 dose:["DPI: 1 inhalation (62.5 mcg) once daily"],
 eff:["24-hr bronchodilation","COPD maintenance"],
 adv:["Nasopharyngitis, URI, cough","Arthralgia, tachycardia","Dry mouth, urinary retention"],
 haz:["Not for asthma or rescue","Narrow-angle glaucoma, BPH","Severe milk-protein allergy (lactose carrier)"],
 dev:["DPI"],
 note:["Ellipta: slide the cover open to load; don't shake; don't block the vent","Component of Anoro and Trelegy Ellipta"]},

/* ---------- COMBINATIONS ---------- */
{c:"combo",g:"Ipratropium bromide + Albuterol",opd:{on:"~15 min",pk:"1–2 hr",du:"4–6 hr"},b:"DuoNeb (neb), Combivent Respimat",t:"SAMA + SABA",
 str:["DuoNeb: 0.5 mg ipratropium + 3 mg albuterol sulfate (= 2.5 mg albuterol) / 3 mL","Combivent: 20 mcg ipratropium / 100 mcg albuterol per actuation"],
 dose:["DuoNeb: 3 mL QID, up to 2 extra doses/day","Combivent Respimat: 1 inhalation QID (max 6/day)"],
 eff:["Additive bronchodilation from two mechanisms","COPD with bronchospasm needing a second bronchodilator"],
 adv:["Combined: tachycardia, tremor, nervousness, dry mouth, headache, cough"],
 haz:["Same as each component: cardiac disease, glaucoma, BPH","Soy/peanut allergy with the old CFC Combivent (discontinued)"],
 dev:["Nebulizer","SMI (Respimat)"],
 note:["DuoNeb is the classic 'give ipratropium and albuterol together' answer","Combines the fast onset of albuterol with the longer action of ipratropium"]},
{c:"combo",g:"Umeclidinium + Vilanterol",opd:{on:"~15 min",pk:"1–3 hr",du:"24 hr"},b:"Anoro Ellipta",t:"LAMA + LABA",
 str:["62.5 mcg umeclidinium / 25 mcg vilanterol"],
 dose:["DPI: 1 inhalation once daily"],
 eff:["24-hr dual bronchodilation","COPD maintenance"],
 adv:["Pharyngitis, sinusitis, URI","Constipation, diarrhea, pain in extremities","Tachycardia, urinary retention"],
 haz:["COPD only: not for asthma (contains LABA without ICS)","Not for rescue","Severe milk-protein allergy"],
 dev:["DPI"],
 note:["Dual bronchodilator, no steroid","Adding fluticasone furoate makes Trelegy (triple therapy)"]},
{c:"combo",g:"Mometasone + Formoterol",opd:{on:"Minutes (formoterol); ICS effect builds over 1–2 wk",pk:"1–3 hr",du:"12 hr"},b:"Dulera",t:"ICS + LABA",
 str:["50/5, 100/5, 200/5 mcg per puff"],
 dose:["pMDI: 2 puffs BID"],
 eff:["Anti-inflammatory control plus 12-hr bronchodilation","Asthma maintenance (≥5 yrs)"],
 adv:["Oral thrush, dysphonia","Nasopharyngitis, sinusitis, headache"],
 haz:["Not for acute bronchospasm","Rinse mouth and spit after use","Shake well; prime before first use"],
 dev:["pMDI"],
 note:["Asthma-labeled combo; not approved for COPD in the US","Use with a spacer to ↓ oral deposition"]},
{c:"combo",g:"Fluticasone propionate + Salmeterol",opd:{on:"30–60 min (salmeterol); ICS effect builds over 1–2 wk",pk:"~3 hr",du:"12 hr"},b:"Advair Diskus, Advair HFA, Wixela Inhub (generic)",t:"ICS + LABA",
 str:["Diskus: 100/50, 250/50, 500/50 mcg","HFA: 45/21, 115/21, 230/21 mcg per puff"],
 dose:["Diskus: 1 inhalation BID","HFA: 2 puffs BID","COPD: 250/50 Diskus BID"],
 eff:["Asthma maintenance","COPD maintenance and ↓ exacerbations (250/50)"],
 adv:["Oral candidiasis (thrush), hoarseness","URI, headache","↑ pneumonia risk in COPD"],
 haz:["Not for rescue","Rinse mouth and spit","High doses: adrenal suppression, bone loss, cataracts/glaucoma"],
 dev:["DPI","pMDI"],
 note:["The classic ICS/LABA board answer","Salmeterol's slow onset means it never replaces albuterol for rescue"]},
{c:"combo",g:"Budesonide + Formoterol",opd:{on:"~15 min (formoterol); ICS effect builds over 1–2 wk",pk:"~2 hr",du:"12 hr"},b:"Symbicort, Breyna (generic)",t:"ICS + LABA",
 str:["80/4.5, 160/4.5 mcg per puff"],
 dose:["pMDI: 2 puffs BID (COPD: 160/4.5)","As maintenance + reliever (SMART): extra puffs PRN per current asthma guidelines"],
 eff:["Asthma maintenance (≥6 yrs)","COPD maintenance"],
 adv:["Oral thrush, dysphonia","Nasopharyngitis, headache, URI","↑ pneumonia risk in COPD"],
 haz:["Rinse mouth and spit","Shake before use; prime if unused 7+ days"],
 dev:["pMDI"],
 note:["Formoterol's fast onset allows single maintenance-and-reliever therapy (SMART) in asthma","Know it as the ICS/LABA combo that can double as reliever"]},

/* ---------- XANTHINES ---------- */
{c:"xan",g:"Theophylline",opd:{on:"IV: immediate · Oral IR: ~30 min",pk:"Oral IR: 1–2 hr · ER: 4–8 hr",du:"IR: 6–8 hr · ER: 12–24 hr"},b:"Theo-24, Elixophyllin, Uniphyl; Aminophylline (IV salt)",t:"Methylxanthine (PDE inhibitor)",
 str:["Oral tabs/caps 100–600 mg (IR and ER)","Therapeutic serum level: 10–20 mcg/mL (many now target 5–15)"],
 dose:["Oral: individualized by serum level; adults often start 300 mg/day in divided doses","IV aminophylline for acute use (rare today)"],
 eff:["Mild bronchodilation","↑ diaphragm contractility, CNS respiratory stimulation, mild diuresis","Add-on for COPD or asthma not controlled on other therapy"],
 adv:["Nausea, vomiting, GI upset","Headache, insomnia, restlessness","Tachycardia, arrhythmias","Seizures (toxicity)"],
 haz:[W("Narrow window")+"Toxic above 20 mcg/mL; monitor serum levels","Levels ↑ with CHF, liver disease, cimetidine, ciprofloxacin, erythromycin, zileuton","Levels ↓ with smoking, phenytoin"],
 dev:["Oral","Injection"],
 note:["Boards test the therapeutic range and signs of toxicity","Largely replaced by inhaled drugs"]},
{c:"xan",g:"Caffeine citrate",opd:{on:"IV: minutes · Oral: ~30 min",pk:"IV: end of infusion · Oral: 30 min–2 hr",du:"~24 hr (neonatal half-life 3–4 days)"},b:"Cafcit",t:"Methylxanthine",
 str:["20 mg/mL caffeine citrate (= 10 mg/mL caffeine base)"],
 dose:["Loading: 20 mg/kg caffeine citrate IV or PO","Maintenance: 5 mg/kg/day (range 5–10) once daily"],
 eff:["Central respiratory stimulant","Apnea of prematurity; aids weaning neonates off the ventilator"],
 adv:["Tachycardia, jitteriness, irritability","Feeding intolerance, vomiting","Watch for necrotizing enterocolitis (NEC)"],
 haz:["Hold or reassess if HR > ~180 in neonates","Caution with seizure disorders, cardiac, renal or hepatic impairment","Therapeutic level ~5–25 mcg/mL"],
 dev:["Injection","Oral"],
 note:["Preferred over theophylline in neonates: wider therapeutic range, once-daily dosing, fewer side effects","Dose on the citrate: 2 mg citrate = 1 mg base"]},

/* ---------- BIOLOGICS ---------- */
{c:"bio",g:"Dupilumab",opd:{on:"FEV₁ improves within ~2 wk",pk:"Serum peak 3–7 days",du:"Dosed every 2 wk"},b:"Dupixent",t:"Monoclonal antibody (anti-IL-4Rα; blocks IL-4 and IL-13)",
 str:["Prefilled syringe/pen: 200 mg/1.14 mL, 300 mg/2 mL"],
 dose:["SC: 400 mg loading then 200 mg every 2 weeks, or 600 mg loading then 300 mg every 2 weeks"],
 eff:["Add-on maintenance for moderate–severe eosinophilic asthma or oral-steroid-dependent asthma (≥6 yrs)","Also COPD with eosinophilia, atopic dermatitis, nasal polyps"],
 adv:["Injection site reactions","Conjunctivitis, keratitis","Transient blood eosinophilia","Oropharyngeal pain, hypersensitivity"],
 haz:["Not for acute bronchospasm","Don't stop systemic or inhaled steroids abruptly when starting","Treat helminth (worm) infections first"],
 dev:["Injection"],
 note:["Targets type 2 (eosinophilic) inflammation","Can be self-injected at home after training"]},
{c:"bio",g:"Omalizumab",opd:{on:"Free IgE drops within hours; clinical benefit by 12–16 wk",pk:"Serum peak 7–8 days",du:"Dosed every 2–4 wk"},b:"Xolair",t:"Monoclonal antibody (anti-IgE)",
 str:["75 mg and 150 mg vials / prefilled syringes"],
 dose:["SC: 75–375 mg every 2 or 4 weeks, based on serum IgE level and body weight"],
 eff:["Moderate–severe persistent allergic asthma (≥6 yrs) with positive skin test to a perennial allergen, poorly controlled on ICS","Also chronic urticaria, nasal polyps, food allergy"],
 adv:["Injection site reactions","URI, sinusitis, headache","Arthralgia"],
 haz:[W("Boxed warning")+"Anaphylaxis: give in a setting ready to treat it; observe after injection; patient carries epinephrine","Not for acute bronchospasm"],
 dev:["Injection"],
 note:["Binds free IgE so it can't trigger mast cells","Dose table uses the pre-treatment IgE level and weight"]},

/* ---------- MAST CELL STABILIZER ---------- */
{c:"masto",g:"Cromolyn sodium",opd:{on:"Protects if given 10–60 min before exposure; full effect 2–4 wk",pk:"~15 min",du:"4–6 hr"},b:"Intal (inhaler discontinued); generic neb; NasalCrom",t:"Mast cell stabilizer (non-steroidal anti-inflammatory)",
 str:["1% solution: 20 mg/2 mL ampule"],
 dose:["SVN: 20 mg QID","Exercise/allergen: 20 mg 10–60 min before exposure"],
 eff:["Prevents mast cell degranulation and mediator release","Prophylaxis of mild persistent asthma, EIB, allergen-triggered asthma"],
 adv:["Cough, throat irritation, wheezing","Unpleasant taste, nasal congestion"],
 haz:["No value in acute attacks","Full benefit takes 2–4 weeks of regular use"],
 dev:["Nebulizer"],
 note:["Very safe: few side effects","Can be mixed with albuterol in the same neb"]},

/* ---------- LEUKOTRIENE MODIFIERS ---------- */
{c:"ltm",g:"Zafirlukast",opd:{on:"Symptoms improve within ~1 wk",pk:"Serum peak ~3 hr",du:"12 hr"},b:"Accolate",t:"Leukotriene receptor antagonist (LTRA)",
 str:["10 mg and 20 mg tablets"],
 dose:["Adults & ≥12 yrs: 20 mg BID","Ages 5–11: 10 mg BID","Take 1 hr before or 2 hr after meals"],
 eff:["Blocks leukotriene receptors: ↓ bronchoconstriction, edema, mucus","Long-term control of mild persistent asthma"],
 adv:["Headache, GI upset, infection","Hepatotoxicity"],
 haz:["Monitor liver function","Interacts with warfarin (↑ PT/INR)","Not for acute attacks","Neuropsychiatric events possible"],
 dev:["Oral"],
 note:["Food ↓ absorption, so take on an empty stomach","Alternative to low-dose ICS"]},
{c:"ltm",g:"Montelukast",opd:{on:"Within 1 day",pk:"Serum peak 3–4 hr",du:"24 hr"},b:"Singulair",t:"Leukotriene receptor antagonist (LTRA)",
 str:["10 mg tablet; 4 mg and 5 mg chewables; 4 mg granules"],
 dose:["≥15 yrs: 10 mg once daily in the evening","6–14 yrs: 5 mg; 2–5 yrs: 4 mg","EIB: dose 2 hr before exercise"],
 eff:["Long-term control of asthma","Prevention of EIB","Allergic rhinitis"],
 adv:["Headache, abdominal pain, URI","Agitation, sleep disturbance, depression"],
 haz:[W("Boxed warning")+"Serious neuropsychiatric events, including suicidal thoughts; watch for mood or behavior changes","Not for acute attacks"],
 dev:["Oral"],
 note:["Most-prescribed leukotriene drug; once daily with no food restriction","Chewables contain phenylalanine (PKU caution)"]},
{c:"ltm",g:"Zileuton",opd:{on:"Within 2 hr",pk:"Serum peak ~2 hr (IR)",du:"IR: 6 hr · CR: 12 hr"},b:"Zyflo, Zyflo CR",t:"5-lipoxygenase inhibitor",
 str:["Zyflo 600 mg tab","Zyflo CR 600 mg ER tab"],
 dose:["IR: 600 mg QID","CR: 1200 mg BID within 1 hr after morning and evening meals","Age ≥12"],
 eff:["Blocks leukotriene synthesis","Long-term control of asthma"],
 adv:["Headache, dyspepsia, nausea","Elevated liver enzymes (ALT)"],
 haz:["Hepatotoxicity: check LFTs before and during therapy","↑ theophylline and warfarin levels","Not for acute attacks"],
 dev:["Oral"],
 note:["Different mechanism from the '-lukasts': stops leukotrienes from being made","QID dosing hurts adherence"]},

/* ---------- ANTI-INFECTIVES ---------- */
{c:"abx",g:"Tobramycin sulfate",opd:{on:"Bactericidal once in the airway",pk:"Sputum ~10 min after neb · serum ~1 hr",du:"12 hr (BID); 28-day on/off cycle"},b:"TOBI, Bethkis, Kitabis Pak, TOBI Podhaler",t:"Aminoglycoside antibiotic",
 str:["TOBI 300 mg/5 mL","Bethkis 300 mg/4 mL","Podhaler 28 mg capsules"],
 dose:["Neb: 300 mg BID for 28 days on, 28 days off","Podhaler: 4 capsules (112 mg) BID, same cycle"],
 eff:["Kills gram-negative bacteria","CF patients colonized with Pseudomonas aeruginosa"],
 adv:["Voice alteration, cough, bronchospasm","Tinnitus, hearing loss (ototoxic)","Nephrotoxicity"],
 haz:["Give a bronchodilator first","Do not mix with other drugs (especially dornase) in the neb","Caution with renal impairment or other ototoxic drugs"],
 dev:["Nebulizer","DPI"],
 note:["CF sequence: bronchodilator → hypertonic saline → dornase → airway clearance → inhaled antibiotic → ICS","Delivered with a PARI LC Plus jet nebulizer"]},
{c:"abx",g:"Pentamidine isethionate",opd:{on:"Protection builds with monthly doses",pk:"Lung level highest right after treatment",du:"4 wk per dose (monthly)"},b:"NebuPent (inhaled), Pentam (IV)",t:"Antiprotozoal / antifungal",
 str:["300 mg vial (powder)"],
 dose:["Neb: 300 mg in 6 mL sterile water every 4 weeks"],
 eff:["Prevention of Pneumocystis jirovecii pneumonia (PCP) in HIV and other immunocompromised patients"],
 adv:["Cough, bronchospasm, wheezing","Metallic / bitter taste","Conjunctivitis, fatigue, dizziness","Pneumothorax (rare)"],
 haz:[W("Caregiver")+"Negative-pressure room or booth; HEPA / expiratory filter; RT wears PPE","Pregnant staff should avoid exposure","Screen patient for TB first","Pre-treat with a bronchodilator"],
 dev:["Nebulizer"],
 note:["Mix with sterile water only: saline makes it precipitate","Delivered via Respirgard II nebulizer (one-way valves + expiratory filter)"]},
{c:"abx",g:"Ribavirin",opd:{on:"Given continuously; slows viral replication",pk:"N/A (continuous aerosol)",du:"12–18 hr/day for 3–7 days"},b:"Virazole",t:"Antiviral",
 str:["6 g vial reconstituted in 300 mL sterile water = 20 mg/mL"],
 dose:["Aerosol via SPAG-2: 12–18 hr/day for 3–7 days"],
 eff:["Severe RSV lower respiratory infection in high-risk infants"],
 adv:["Worsening respiratory function, bronchospasm","Conjunctivitis, rash","Anemia (systemic)"],
 haz:[W("Teratogenic")+"Pregnant caregivers and visitors must avoid exposure","Scavenging tent or negative-pressure room","Drug crystallizes in ventilator circuits and valves: use filters and change them often"],
 dev:["Nebulizer (SPAG-2)"],
 note:["SPAG = small particle aerosol generator","Rarely used now; RSV prevention (palivizumab, nirsevimab) is more common"]},
{c:"abx",g:"Aztreonam lysine",opd:{on:"Bactericidal once in the airway",pk:"Sputum ~10 min after neb · serum ~1 hr",du:"8 hr (TID); 28-day on/off cycle"},b:"Cayston",t:"Monobactam antibiotic",
 str:["75 mg vial + 1 mL diluent"],
 dose:["Neb: 75 mg TID (doses at least 4 hr apart) for 28 days on, 28 days off"],
 eff:["Improves respiratory symptoms in CF patients (≥7 yrs) with Pseudomonas aeruginosa"],
 adv:["Cough, nasal congestion, wheezing","Pharyngolaryngeal pain, fever","Bronchospasm, chest discomfort"],
 haz:["Give a bronchodilator 15 min–4 hr before","Allergic reactions (caution with ceftazidime allergy)","Refrigerate; reconstitute just before use"],
 dev:["Nebulizer (Altera)"],
 note:["Only given with the Altera vibrating-mesh nebulizer","Often alternated month-to-month with tobramycin"]},
{c:"abx",g:"Colistin (colistimethate sodium)",opd:{on:"Bactericidal once in the airway",pk:"Sputum within ~1 hr of neb",du:"12 hr (BID)"},b:"Coly-Mycin M",t:"Polymyxin antibiotic",
 str:["150 mg colistin base activity per vial"],
 dose:["Inhaled (off-label): 75–150 mg BID via neb","IV: 2.5–5 mg/kg/day in divided doses"],
 eff:["Multidrug-resistant gram-negative infections: Pseudomonas, Acinetobacter, Klebsiella","CF Pseudomonas; ventilator-associated pneumonia"],
 adv:["Bronchospasm, chest tightness, cough","Nephrotoxicity, neurotoxicity (systemic)","Paresthesias, neuromuscular blockade"],
 haz:["Mix immediately before use: premixed solution breaks down into a form toxic to the lungs","Pre-treat with a bronchodilator","Monitor renal function"],
 dev:["Nebulizer","Injection"],
 note:["A 'last-resort' antibiotic for resistant organisms","Neuromuscular blockade risk: watch ventilation"]},
{c:"abx",g:"Nafcillin",opd:{on:"IV: immediate",pk:"End of infusion (IM: 30–60 min)",du:"4–6 hr (half-life 0.5–1 hr)"},b:"Nallpen (generic nafcillin)",t:"Penicillinase-resistant penicillin",
 str:["1 g and 2 g vials / premixed bags"],
 dose:["IV: 1–2 g every 4–6 hr"],
 eff:["Infections from methicillin-sensitive Staphylococcus aureus (MSSA): staph pneumonia, endocarditis, osteomyelitis, bacteremia"],
 adv:["Hypersensitivity / anaphylaxis","Phlebitis; tissue necrosis if extravasated","Neutropenia, hypokalemia, interstitial nephritis"],
 haz:["Contraindicated with penicillin allergy","Not effective against MRSA","Check IV site often"],
 dev:["Injection"],
 note:["Systemic only; not inhaled","Know it as the anti-staph penicillin"]},
{c:"abx",g:"Gentamicin",opd:{on:"IV: immediate",pk:"~30 min after a 30-min infusion (IM: 30–90 min)",du:"8 hr traditional · 24 hr extended-interval"},b:"Garamycin (generic gentamicin)",t:"Aminoglycoside antibiotic",
 str:["40 mg/mL injection (10 mg/mL pediatric)"],
 dose:["IV/IM: 5–7 mg/kg once daily (extended interval), or 1–1.7 mg/kg q8h","Aerosolized (off-label) in some protocols"],
 eff:["Serious gram-negative infections (Pseudomonas, E. coli, Klebsiella)","Synergy with β-lactams for gram-positive infections"],
 adv:["Ototoxicity (hearing loss, vertigo)","Nephrotoxicity","Neuromuscular blockade"],
 haz:["Monitor peak and trough levels plus renal function","Can potentiate paralytics → respiratory depression; caution in myasthenia gravis","Avoid other nephrotoxic / ototoxic drugs"],
 dev:["Injection"],
 note:["Same class and toxicities as tobramycin","'Mycin' spelling is used for Streptomyces-derived drugs; gentamicin comes from Micromonospora"]},

/* ---------- MUCOLYTICS ---------- */
{c:"muco",g:"Acetylcysteine",opd:{on:"~1 min",pk:"5–10 min",du:"Short; repeat TID–QID"},b:"Mucomyst; Acetadote (IV)",t:"Mucolytic",
 str:["10% and 20% solution"],
 dose:["Neb: 3–5 mL of 20% or 6–10 mL of 10%, TID–QID","Direct instillation: 1–2 mL of 10–20% every 1–4 hr"],
 eff:["Breaks disulfide bonds in mucoproteins → thinner mucus","Thick, tenacious secretions (bronchitis, pneumonia, atelectasis from mucus plugs)","Antidote for acetaminophen overdose (oral/IV)"],
 adv:["Bronchospasm (most important)","Rotten-egg (sulfur) odor, nausea, vomiting","Stomatitis, rhinorrhea, hemoptysis"],
 haz:[W("Bronchospasm")+"Always give with or after a bronchodilator","Have suction ready: secretions can increase quickly","Opened vials: refrigerate and discard after 96 hr"],
 dev:["Nebulizer","Direct instillation"],
 note:["Light purple color change in the vial is harmless","Reacts with rubber and some metals"]},
{c:"muco",g:"Dornase alfa",opd:{on:"Sputum thins within hours; lung function improves in 3–7 days",pk:"Sputum level ~15 min after neb",du:"24 hr (once daily)"},b:"Pulmozyme",t:"Mucolytic enzyme (recombinant DNase)",
 str:["2.5 mg/2.5 mL (1 mg/mL) ampule"],
 dose:["Neb: 2.5 mg once daily (some patients BID)"],
 eff:["Cleaves extracellular DNA from dead neutrophils in purulent sputum","Cystic fibrosis: improves lung function and ↓ infections"],
 adv:["Voice alteration, pharyngitis, laryngitis","Chest pain, rash, conjunctivitis"],
 haz:["Do not mix or dilute with other drugs in the nebulizer","Refrigerate and protect from light","Use an approved jet neb, not an ultrasonic nebulizer"],
 dev:["Nebulizer"],
 note:["CF-specific; not shown to help non-CF bronchiectasis","Given before airway clearance so it has time to work"]},

/* ---------- CORTICOSTEROIDS ---------- */
{c:"ster",g:"Flunisolide",opd:{on:"Days (24 hr–1 wk)",pk:"1–4 wk",du:"12 hr (BID)"},b:"AeroBid, Aerospan (discontinued); nasal spray",t:"Inhaled corticosteroid (ICS)",
 str:["Aerospan 80 mcg/puff","AeroBid 250 mcg/puff","Nasal 25 mcg/spray"],
 dose:["Aerospan: 2 puffs (160 mcg) BID","AeroBid: 2 puffs BID"],
 eff:["Long-term control of persistent asthma (anti-inflammatory)"],
 adv:["Oral thrush, dysphonia, cough","Unpleasant taste, headache"],
 haz:["Not for acute bronchospasm","Rinse mouth and spit"],
 dev:["pMDI"],
 note:["Aerospan had a built-in spacer","Oral inhalers discontinued in US; still appears in study guides"]},
{c:"ster",g:"Triamcinolone acetonide",opd:{on:"Days (~1 wk)",pk:"1–2 wk",du:"6–12 hr (TID–QID dosing)"},b:"Azmacort (discontinued); Kenalog (inj.), Nasacort (nasal)",t:"Corticosteroid (ICS / systemic)",
 str:["Azmacort 75 mcg/puff (100 mcg from valve)","Kenalog 10 & 40 mg/mL"],
 dose:["Azmacort: 2 puffs TID–QID or 4 puffs BID"],
 eff:["Long-term control of persistent asthma","Injectable: anti-inflammatory for many conditions"],
 adv:["Oral thrush, dysphonia, cough","Systemic: hyperglycemia, fluid retention"],
 haz:["Not for acute attacks","Rinse and spit after inhaled use"],
 dev:["pMDI","Injection"],
 note:["Azmacort had a built-in spacer tube","Inhaled form discontinued in US (2010)"]},
{c:"ster",g:"Budesonide",opd:{on:"Flexhaler: ~24 hr · Respules: 2–8 days",pk:"1–2 wk (Respules up to 4–6 wk)",du:"12–24 hr"},b:"Pulmicort Respules, Pulmicort Flexhaler",t:"Inhaled corticosteroid (ICS)",
 str:["Respules 0.25, 0.5, 1 mg/2 mL suspension","Flexhaler 90 and 180 mcg/inh"],
 dose:["Respules: 0.25–1 mg once daily or BID (ages 12 mo–8 yrs)","Flexhaler: 180–360 mcg BID (max 720 mcg BID)"],
 eff:["Long-term control of persistent asthma","Respules are used for young children who can't use inhalers"],
 adv:["Oral thrush, dysphonia, cough","Respiratory infection, otitis media (peds)"],
 haz:["Not for acute bronchospasm","Wash face and rinse mouth after a mask treatment","Suspension: don't use an ultrasonic nebulizer"],
 dev:["Nebulizer","DPI"],
 note:["The only nebulized ICS in the US","Mask treatments leave steroid on the face; wipe it off"]},
{c:"ster",g:"Beclomethasone dipropionate",opd:{on:"1–2 days",pk:"1–4 wk",du:"12 hr (BID)"},b:"QVAR RediHaler",t:"Inhaled corticosteroid (ICS)",
 str:["40 and 80 mcg/actuation"],
 dose:["40–320 mcg BID (age-based)"],
 eff:["Long-term control of persistent asthma (≥4 yrs)"],
 adv:["Oral thrush, dysphonia","Headache, URI, pharyngitis"],
 haz:["Not for acute attacks","Rinse and spit","High doses: adrenal suppression, growth slowing in children"],
 dev:["pMDI (breath-actuated)"],
 note:["RediHaler is breath-actuated: do NOT shake and do NOT use with a spacer","HFA propellant gives fine particles with good lung deposition"]},
{c:"ster",g:"Fluticasone",opd:{on:"~24 hr",pk:"1–2 wk",du:"Propionate: 12 hr · Furoate: 24 hr"},b:"Flovent HFA / Diskus (propionate); Arnuity Ellipta (furoate); ArmonAir Digihaler",t:"Inhaled corticosteroid (ICS)",
 str:["HFA 44, 110, 220 mcg/puff","Diskus 50, 100, 250 mcg","Arnuity 50, 100, 200 mcg"],
 dose:["HFA: 88–880 mcg BID","Diskus: 100–1000 mcg BID","Arnuity: 1 inhalation once daily"],
 eff:["Long-term control of persistent asthma","Anti-inflammatory; ↓ airway hyperresponsiveness"],
 adv:["Oral thrush, dysphonia, cough","Headache, URI","Pneumonia risk in COPD"],
 haz:["Not for acute bronchospasm","Rinse and spit; use a spacer with the pMDI","High doses: adrenal suppression, bone loss, cataracts"],
 dev:["pMDI","DPI"],
 note:["One of the most potent ICSs","Flovent HFA brand ended in 2024; authorized generics remain"]},
{c:"ster",g:"Methylprednisolone",opd:{on:"IV: ~1 hr; clinical effect 4–6 hr",pk:"IV: 30 min–1 hr · Oral: 1–2 hr",du:"12–36 hr"},b:"Solu-Medrol (IV), Medrol (oral), Depo-Medrol (IM)",t:"Systemic corticosteroid",
 str:["Solu-Medrol 40, 125, 500, 1000 mg vials","Medrol 2–32 mg tablets"],
 dose:["Acute asthma: 40–80 mg/day IV or PO in 1–2 doses (peds 1–2 mg/kg/day)","COPD exacerbation: often 40–125 mg IV, then switch to oral"],
 eff:["Powerful anti-inflammatory","Acute asthma and COPD exacerbations, status asthmaticus, airway edema"],
 adv:["Hyperglycemia, fluid retention, HTN","Insomnia, mood changes, ↑ appetite","Immunosuppression"],
 haz:["Taper if used longer than about 2 weeks (adrenal suppression)","Monitor glucose, especially in diabetics","Long-term: osteoporosis, cataracts, muscle weakness, Cushingoid features, GI ulcers"],
 dev:["Injection","Oral"],
 note:["Onset takes 4–6 hr, so give early in the exacerbation","IV and oral routes work equally well if the patient can swallow"]},
{c:"ster",g:"Prednisone",opd:{on:"1–2 hr; clinical effect 4–6 hr",pk:"1–2 hr",du:"12–36 hr"},b:"Deltasone (discontinued), Rayos; generic",t:"Systemic corticosteroid",
 str:["1, 2.5, 5, 10, 20, 50 mg tablets; oral solution"],
 dose:["COPD exacerbation: 40 mg daily for 5 days","Asthma burst: 40–60 mg/day for 5–10 days"],
 eff:["Oral anti-inflammatory","Asthma and COPD exacerbations; steroid-dependent severe asthma"],
 adv:["Same as methylprednisolone: hyperglycemia, fluid retention, mood changes, insomnia, immunosuppression"],
 haz:["Taper after long courses","Take with food to limit GI upset","Long-term: osteoporosis, cataracts, adrenal suppression"],
 dev:["Oral"],
 note:["Short bursts (≤ ~10 days) usually don't need a taper","Prodrug converted to prednisolone in the liver"]},

/* ---------- DILUENTS ---------- */
{c:"dil",g:"Normal saline solution",opd:{on:"Immediate",pk:"N/A",du:"Only while aerosol is delivered"},b:"0.9% NaCl (isotonic)",t:"Diluent / bland aerosol",
 str:["0.9%"],
 dose:["Diluent: 2–5 mL with nebulized meds","Bland aerosol or instillation: 3–5 mL"],
 eff:["Dilutes medications for nebulization","Humidifies and thins secretions","Sputum induction (with hypertonic preferred)"],
 adv:["Minimal; rare bronchospasm","Contamination risk with multi-dose containers"],
 haz:["Use sterile unit doses","Overhydration with prolonged continuous aerosol in infants"],
 dev:["Nebulizer","Direct instillation"],
 note:["Isotonic: matches body fluid, so the least irritating diluent","Routine instillation before suctioning is no longer recommended"]},
{c:"dil",g:"Hypertonic saline solution",opd:{on:"Immediate",pk:"Within 1 hr",du:"Clearance effect lasts up to ~8 hr"},b:"3%, 3.5%, 7% NaCl (Hyper-Sal, PulmoSal)",t:"Bland aerosol / airway hydration",
 str:["3%, 3.5%, 7%"],
 dose:["Sputum induction: 3–5 mL of 3%","CF: 4 mL of 7% BID"],
 eff:["Draws water into the airway surface liquid → better mucociliary clearance","Sputum induction (TB, PCP, cytology)","Airway clearance in CF"],
 adv:["Bronchospasm (asthma, COPD)","Cough, throat irritation, salty taste"],
 haz:["Pre-treat with albuterol","Monitor for wheezing; stop if bronchospasm develops","Sputum induction for TB: isolation room, N95"],
 dev:["Nebulizer"],
 note:["Hypertonic = more than 0.9% salt","Given before dornase and airway clearance in CF"]},
{c:"dil",g:"Sterile water",opd:{on:"Immediate",pk:"N/A",du:"Only while aerosol is delivered"},b:"USP sterile water for inhalation",t:"Bland aerosol / humidifier fluid",
 str:["Hypotonic (0% NaCl)"],
 dose:["Large-volume nebulizers and heated humidifiers: continuous","Diluent for pentamidine and ribavirin"],
 eff:["Humidification for artificial airways, oxygen therapy, and bypassed upper airways","Helps thin secretions"],
 adv:["Airway irritation and bronchospasm (hypotonic)","Overhydration (especially infants)"],
 haz:["Caution in reactive airways","Contamination risk: keep the system closed","Watch for condensation in tubing (drain away from the patient)"],
 dev:["Nebulizer","Humidifier"],
 note:["The required diluent when saline would precipitate a drug (pentamidine)","Sterile = free of microorganisms"]},
{c:"dil",g:"Distilled water",opd:{on:"Immediate",pk:"N/A",du:"Only while humidifier runs"},b:"(Not a drug product)",t:"Humidifier fluid",
 str:["Hypotonic (0% NaCl)"],
 dose:["Fills home humidifiers and home CPAP humidifier chambers"],
 eff:["Mineral-free water that won't leave scale in equipment","Home humidification"],
 adv:["Airway irritation if aerosolized"],
 haz:["Not sterile: never use to dilute inhaled medications","Infection risk if reservoir is not cleaned and refilled daily"],
 dev:["Humidifier"],
 note:["Exam distinction: distilled = minerals removed; sterile = microorganisms removed","Hospital equipment uses sterile water"]}
];
